import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        // Core Ink & Amber tokens
        ink: {
          DEFAULT: '#161311',
          stone: '#1C1917',
          card: '#1E1B19',
          panel: '#292524',
          lighter: '#2A2624',
          border: '#383432',
          divider: '#44403C',
          muted: '#78716C',
        },
        parchment: {
          DEFAULT: '#F5F1E8',
          light: '#FAF7F2',
          card: '#FFFFFF',
          border: '#E2DDD3',
          subtle: '#EDE8DE',
          recessed: '#EDE7DC',
          edge: '#D6CEBE',
          text: '#1C1917',
          muted: '#666059',
        },
        amber: {
          DEFAULT: '#D97706',
          glow: '#B45309',
          light: '#F59E0B',
          soft: '#FEF3C7',
          dark: '#451A03',
        },
        forest: {
          DEFAULT: '#166534',
          soft: '#DCFCE7',
          border: '#86EFAC',
          dark: '#052E16',
          bright: '#4ADE80',
        },
        rust: {
          DEFAULT: '#991B1B',
          soft: '#FEE2E2',
          border: '#FCA5A5',
          dark: '#450A0A',
          bright: '#F87171',
        },

        // Material / Stitch surface tokens
        surface: '#161311',
        'surface-dim': '#161311',
        'surface-bright': '#3c3836',
        'surface-container-lowest': '#100e0c',
        'surface-container-low': '#1e1b19',
        'surface-container': '#221f1d',
        'surface-container-high': '#2d2927',
        'surface-container-highest': '#383432',
        'surface-variant': '#383432',
        'on-surface': '#e9e1dd',
        'on-surface-variant': '#dbc2b0',
        'inverse-surface': '#e9e1dd',
        'inverse-on-surface': '#33302d',
        'outline': '#a38c7c',
        'outline-variant': '#554336',
        'surface-tint': '#ffb77d',
        'background': '#161311',
        'on-background': '#e9e1dd',

        // Primary / Secondary / Tertiary / Error tokens
        primary: '#ffb77d',
        'on-primary': '#4d2600',
        'primary-container': '#d97707',
        'on-primary-container': '#432100',
        'inverse-primary': '#904d00',
        'primary-fixed': '#ffdcc3',
        'primary-fixed-dim': '#ffb77d',
        secondary: '#8bd79b',
        'on-secondary': '#003918',
        'secondary-container': '#005829',
        'on-secondary-container': '#81cc90',
        'secondary-fixed': '#a6f4b5',
        'secondary-fixed-dim': '#8bd79b',
        tertiary: '#ffb4ac',
        'on-tertiary': '#690007',
        'tertiary-container': '#f55e55',
        'on-tertiary-container': '#5c0005',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
      },
      fontFamily: {
        belgina: ['Belgina', 'Georgia', 'serif'],
        wapilor: ['Wapilor', 'sans-serif'],
        bevas: ['Bevas', 'Bebas Neue', 'sans-serif'],
        logo: ['Wapilor', 'sans-serif'],
        display: ['EB Garamond', 'Fraunces', 'Georgia', 'serif'],
        headline: ['EB Garamond', 'Fraunces', 'Georgia', 'serif'],
        'headline-xl': ['EB Garamond', 'Fraunces', 'serif'],
        'headline-lg': ['EB Garamond', 'Fraunces', 'serif'],
        'headline-md': ['EB Garamond', 'Fraunces', 'serif'],
        body: ['Plus Jakarta Sans', 'Inter', 'sans-serif'],
        'body-lg': ['Plus Jakarta Sans', 'Inter', 'sans-serif'],
        'body-md': ['Plus Jakarta Sans', 'Inter', 'sans-serif'],
        'body-sm': ['Plus Jakarta Sans', 'Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        label: ['JetBrains Mono', 'monospace'],
        'label-sm': ['JetBrains Mono', 'monospace'],
        'label-md': ['JetBrains Mono', 'monospace'],
        'label-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'contract-clause': ['EB Garamond', 'serif'],
      },
      fontSize: {
        'label-sm': ['10px', { lineHeight: '14px', letterSpacing: '0.06em', fontWeight: '600' }],
        'label-md': ['11px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '500' }],
        'label-lg': ['13px', { lineHeight: '18px', letterSpacing: '0.02em', fontWeight: '600' }],
        'body-sm': ['12px', { lineHeight: '18px', letterSpacing: '0.01em', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '22px', letterSpacing: '0em', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '26px', letterSpacing: '-0.005em', fontWeight: '400' }],
        'headline-md': ['22px', { lineHeight: '28px', letterSpacing: '0em', fontWeight: '600' }],
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'headline-xl': ['36px', { lineHeight: '44px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'contract-clause': ['17px', { lineHeight: '28px', letterSpacing: '0.01em', fontWeight: '400' }],
      },
      borderRadius: {
        DEFAULT: '0.25rem', // 4px sharp
        sm: '0.125rem',     // 2px
        md: '0.375rem',     // 6px
        lg: '0.5rem',       // 8px
        xl: '0.75rem',      // 12px
        full: '9999px',
      },
      spacing: {
        'sidebar-width': '20rem',
        'terminal-rail-width': '4.5rem',
        'document-max-width': '54rem',
        'gutter-desktop': '1.5rem',
        'gutter-mobile': '1rem',
        'space-2xs': '0.125rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '0.75rem',
        'space-base': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
        'space-2xl': '3rem',
        'space-3xl': '4rem',
      },
    },
  },
  plugins: [],
};

export default config;
