"""
Agent 3: Arbiter-3 — AI Judge & Deal Mediator.

Consumes upstream outputs from Agent 1 (Party A baseline), Agent 2 (Party B
risk analysis), matter financial context, and scored negotiation candidates
to produce a dual-lens verdict for every contested clause.

Two independent analysis lenses:
    LEGAL   — liability, indemnity, jurisdiction, evidence context, legal risk
    COMMERCIAL — ARR impact, payment/float impact, relationship, commercial risk

Then synthesises:
    • Recommended compromise candidate
    • Rationale with clause_id and evidence references
    • Candidate comparison matrix
    • Confidence level
    • Proposed clause language

Design constraints:
    • Every claim MUST reference a clause_id or evidence source
    • No invented laws, precedents, or citations are presented as facts
    • Human review remains mandatory — output explicitly flags this
    • LLM prompts are short and structured
    • Deterministic fallback when no LLM key is configured
"""

import json
import logging
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field

from app.agents.base_agent import BaseAgent, EventCallback
from app.agents.agent1_ingestor_a import ClassifiedClause, LexIngestorAOutput
from app.agents.agent2_ingestor_b import (
    ClauseRiskProfile,
    LexIngestorBOutput,
    RiskFinding,
)
from app.config import settings
from app.services.negotiation_engine import (
    ClauseNegotiationResult,
    CompromiseCandidate,
    CompromiseStrategy,
    NegotiationEngineOutput,
    UtilityScores,
)

logger = logging.getLogger(__name__)


# ═════════════════════════════════════════════════════════════════════════════
# Pydantic Output Models
# ═════════════════════════════════════════════════════════════════════════════

# ── Legal Lens ───────────────────────────────────────────────────────────────

class LiabilityAnalysis(BaseModel):
    """Legal assessment of liability exposure for a clause."""
    clause_id: str
    exposure_summary: str = ""
    cap_status: str = ""          # e.g. "capped at 1x ARR", "uncapped", "mutual"
    consequential_damages: str = ""
    risk_level: str = "moderate"  # low | moderate | high | critical
    referenced_clauses: List[str] = Field(default_factory=list)


class IndemnityAnalysis(BaseModel):
    """Legal assessment of indemnification obligations."""
    clause_id: str
    scope_summary: str = ""
    trigger_conditions: str = ""
    cap_or_limit: str = ""
    survival_period: str = ""
    risk_level: str = "moderate"
    referenced_clauses: List[str] = Field(default_factory=list)


class JurisdictionAnalysis(BaseModel):
    """Legal assessment of venue / governing law provisions."""
    clause_id: str
    governing_law: str = ""
    venue: str = ""
    arbitration_clause: str = ""
    jury_waiver: bool = False
    risk_level: str = "moderate"
    referenced_clauses: List[str] = Field(default_factory=list)


class LegalLens(BaseModel):
    """Complete legal-lens analysis for a single clause."""
    clause_id: str
    liability: Optional[LiabilityAnalysis] = None
    indemnity: Optional[IndemnityAnalysis] = None
    jurisdiction: Optional[JurisdictionAnalysis] = None
    evidence_references: List[str] = Field(
        default_factory=list,
        description="Clause IDs, risk flags, or external evidence keys cited.",
    )
    legal_risk_score: float = Field(default=0.0, ge=0.0, le=10.0)
    legal_summary: str = ""
    disclaimer: str = (
        "This analysis is generated by an AI system and does not constitute "
        "legal advice.  Human counsel review is mandatory before any action."
    )


# ── Commercial Lens ─────────────────────────────────────────────────────────

class ArrImpact(BaseModel):
    """Impact assessment on annual recurring revenue / account value."""
    clause_id: str
    deal_value_at_risk: str = ""
    arr_exposure_pct: float = Field(
        default=0.0, ge=0.0, le=100.0,
        description="Estimated percentage of ARR at risk from this clause.",
    )
    narrative: str = ""
    referenced_clauses: List[str] = Field(default_factory=list)


class PaymentFloatImpact(BaseModel):
    """Impact of payment term changes on cash-flow and float."""
    clause_id: str
    baseline_terms: str = ""
    proposed_terms: str = ""
    float_delta_days: int = 0
    cash_flow_narrative: str = ""
    referenced_clauses: List[str] = Field(default_factory=list)


class RelationshipImpact(BaseModel):
    """Assessment of how a clause outcome affects the commercial relationship."""
    clause_id: str
    relationship_risk: str = "neutral"  # positive | neutral | negative | adversarial
    narrative: str = ""
    referenced_clauses: List[str] = Field(default_factory=list)


class CommercialLens(BaseModel):
    """Complete commercial-lens analysis for a single clause."""
    clause_id: str
    arr_impact: Optional[ArrImpact] = None
    payment_float: Optional[PaymentFloatImpact] = None
    relationship: Optional[RelationshipImpact] = None
    commercial_risk_score: float = Field(default=0.0, ge=0.0, le=10.0)
    commercial_summary: str = ""


# ── Candidate Comparison ────────────────────────────────────────────────────

class CandidateComparison(BaseModel):
    """Side-by-side comparison entry in the verdict."""
    strategy: str
    label: str
    party_a_utility: float = 0.0
    party_b_utility: float = 0.0
    compromise_score: float = 0.0
    is_recommended: bool = False
    is_pareto_efficient: bool = False
    disqualification_reason: str = ""


# ── Per-Clause Verdict ──────────────────────────────────────────────────────

class ClauseVerdict(BaseModel):
    """The Arbiter's full verdict for a single clause."""
    clause_id: str
    section_number: str = ""
    title: str = ""
    category: str = "general"

    # Dual-lens analyses
    legal_lens: LegalLens
    commercial_lens: CommercialLens

    # Recommendation
    recommended_strategy: str = ""
    recommended_label: str = ""
    proposed_clause_text: str = ""
    rationale: str = ""
    confidence: float = Field(
        default=0.0, ge=0.0, le=100.0,
        description="Arbiter confidence in this recommendation (0–100%).",
    )
    requires_human_review: bool = True

    # Candidate comparison matrix
    candidate_comparison: List[CandidateComparison] = Field(default_factory=list)

    # Combined risk
    combined_risk_score: float = Field(
        default=0.0, ge=0.0, le=10.0,
        description="Blended legal + commercial risk: 0.55 × legal + 0.45 × commercial.",
    )

    # Traceability
    evidence_cited: List[str] = Field(
        default_factory=list,
        description="All clause_ids, risk flags, or evidence keys referenced in this verdict.",
    )


# ── Full Agent Output ───────────────────────────────────────────────────────

class ArbiterOutput(BaseModel):
    """Structured output of Agent 3: Arbiter-3."""
    matter_id: Optional[str] = None
    verdicts: List[ClauseVerdict] = Field(default_factory=list)
    aggregate_legal_risk: float = Field(default=0.0, ge=0.0, le=10.0)
    aggregate_commercial_risk: float = Field(default=0.0, ge=0.0, le=10.0)
    aggregate_combined_risk: float = Field(default=0.0, ge=0.0, le=10.0)
    aggregate_confidence: float = Field(default=0.0, ge=0.0, le=100.0)
    escalated_clause_ids: List[str] = Field(default_factory=list)
    executive_summary: str = ""
    human_review_required: bool = True


# ═════════════════════════════════════════════════════════════════════════════
# Deterministic Analysis Helpers
# ═════════════════════════════════════════════════════════════════════════════

def _build_legal_lens(
    clause_id: str,
    category: str,
    a_clause: Optional[ClassifiedClause],
    risk_profile: Optional[ClauseRiskProfile],
    findings: List[RiskFinding],
    evidence: List[Dict[str, Any]],
) -> LegalLens:
    """Deterministically build the legal-lens analysis from upstream data."""
    evidence_refs: List[str] = [clause_id]
    legal_risk = risk_profile.composite_risk_score if risk_profile else 0.0

    liability = None
    indemnity = None
    jurisdiction = None

    # Aggregate risk flags from all findings for this clause
    all_flags = []
    for f in findings:
        all_flags.extend(f.deterministic_flags)
        evidence_refs.append(f.clause_id)

    # Add any external evidence references
    for ev in evidence:
        ev_id = ev.get("evidence_id", ev.get("id", ""))
        if ev_id:
            evidence_refs.append(ev_id)

    evidence_refs = list(dict.fromkeys(evidence_refs))  # deduplicate, preserve order

    # ── Liability sub-analysis ───────────────────────────────────────
    if category == "liability" or any(
        f.category == "liability" for f in findings
    ):
        liability_findings = [f for f in findings if f.category == "liability"]
        cap_status = "baseline terms"
        if any("uncapped" in fl or "unlimited" in fl or "no cap" in fl for fl in all_flags):
            cap_status = "uncapped — Party B removed liability cap"
        elif any("cap" in fl or "1x" in fl for fl in all_flags):
            cap_status = "capped (baseline preserved)"

        consequential = "not addressed"
        if any("consequential" in fl for fl in all_flags):
            consequential = "consequential damages included — elevated exposure"
        elif any("waive" in fl for fl in all_flags):
            consequential = "consequential damages waived"

        liability = LiabilityAnalysis(
            clause_id=clause_id,
            exposure_summary=(
                f"Liability analysis for {clause_id}: "
                f"{len(liability_findings)} finding(s) detected.  "
                f"Cap status: {cap_status}."
            ),
            cap_status=cap_status,
            consequential_damages=consequential,
            risk_level=_risk_label(legal_risk),
            referenced_clauses=evidence_refs[:10],
        )

    # ── Indemnity sub-analysis ───────────────────────────────────────
    if category == "indemnification" or any(
        f.category == "indemnification" for f in findings
    ):
        indemnity_findings = [f for f in findings if f.category == "indemnification"]
        scope = "standard mutual indemnification"
        if any("sole" in fl or "unlimited" in fl or "broadened" in fl for fl in all_flags):
            scope = "broadened / one-sided indemnification — elevated obligation"

        indemnity = IndemnityAnalysis(
            clause_id=clause_id,
            scope_summary=(
                f"Indemnity analysis for {clause_id}: "
                f"{len(indemnity_findings)} finding(s).  Scope: {scope}."
            ),
            trigger_conditions="Per contract terms (see referenced clauses).",
            cap_or_limit="Subject to overall liability cap unless modified.",
            survival_period="Per contract survival provisions.",
            risk_level=_risk_label(legal_risk),
            referenced_clauses=evidence_refs[:10],
        )

    # ── Jurisdiction sub-analysis ────────────────────────────────────
    if category == "venue_jurisdiction" or category == "governing_law" or any(
        f.category == "venue_jurisdiction" for f in findings
    ):
        jury_waiver = any("jury" in fl or "waive jury" in fl for fl in all_flags)
        arb = "none specified"
        if any("arbitration" in fl for fl in all_flags):
            arb = "mandatory arbitration clause detected"

        jurisdiction = JurisdictionAnalysis(
            clause_id=clause_id,
            governing_law="Per contract — see referenced clause.",
            venue="Per contract — Party B may have proposed venue change.",
            arbitration_clause=arb,
            jury_waiver=jury_waiver,
            risk_level=_risk_label(legal_risk * 0.8),
            referenced_clauses=evidence_refs[:10],
        )

    # ── Summary ──────────────────────────────────────────────────────
    summary_parts = []
    if liability:
        summary_parts.append(f"Liability: {liability.cap_status}")
    if indemnity:
        summary_parts.append(f"Indemnity: {indemnity.scope_summary[:80]}")
    if jurisdiction:
        summary_parts.append(f"Jurisdiction: arbitration={jurisdiction.arbitration_clause[:40]}")
    if not summary_parts:
        summary_parts.append(
            f"No specialised legal findings for {clause_id} "
            f"(category: {category}, risk: {legal_risk:.1f}/10)."
        )

    return LegalLens(
        clause_id=clause_id,
        liability=liability,
        indemnity=indemnity,
        jurisdiction=jurisdiction,
        evidence_references=evidence_refs,
        legal_risk_score=round(min(legal_risk, 10.0), 2),
        legal_summary="; ".join(summary_parts),
    )


def _build_commercial_lens(
    clause_id: str,
    category: str,
    risk_profile: Optional[ClauseRiskProfile],
    findings: List[RiskFinding],
    financial_context: Dict[str, Any],
) -> CommercialLens:
    """Deterministically build the commercial-lens analysis."""
    risk_score = risk_profile.composite_risk_score if risk_profile else 0.0
    arr_value = financial_context.get("arr_value", "")
    variance_ceiling = financial_context.get("variance_ceiling")

    evidence_refs: List[str] = [clause_id]

    # ── ARR Impact ───────────────────────────────────────────────────
    arr_exposure_pct = 0.0
    arr_narrative = "No material ARR impact identified."
    if category in ("liability", "indemnification") and risk_score >= 4.0:
        arr_exposure_pct = min(risk_score * 8.0, 80.0)
        arr_narrative = (
            f"Clause {clause_id} risk score {risk_score:.1f}/10 creates potential "
            f"exposure of ~{arr_exposure_pct:.0f}% of contract value "
            f"({'ARR: ' + arr_value if arr_value else 'ARR not specified'})."
        )
    elif category == "payment" and risk_score >= 3.0:
        arr_exposure_pct = min(risk_score * 5.0, 50.0)
        arr_narrative = (
            f"Payment term changes in {clause_id} may affect cash-flow by "
            f"~{arr_exposure_pct:.0f}% of deal value."
        )
    elif category == "termination" and risk_score >= 5.0:
        arr_exposure_pct = min(risk_score * 10.0, 100.0)
        arr_narrative = (
            f"Termination provisions in {clause_id} could put up to "
            f"~{arr_exposure_pct:.0f}% of ARR at risk if triggered."
        )

    arr_impact = ArrImpact(
        clause_id=clause_id,
        deal_value_at_risk=arr_value or "Not specified",
        arr_exposure_pct=round(arr_exposure_pct, 1),
        narrative=arr_narrative,
        referenced_clauses=evidence_refs,
    )

    # ── Payment / Float Impact ───────────────────────────────────────
    payment_float = None
    if category == "payment":
        payment_findings = [f for f in findings if f.category == "payment"]
        baseline = "Per Party A standard terms"
        proposed = "Per Party B redline"
        float_delta = 0
        for f in payment_findings:
            for flag in f.deterministic_flags:
                flag_l = flag.lower()
                if "net 10" in flag_l:
                    float_delta = -50  # 50 days earlier than Net 60
                elif "net 15" in flag_l:
                    float_delta = -45
                elif "net 7" in flag_l:
                    float_delta = -53
                elif "immediate" in flag_l or "upon receipt" in flag_l:
                    float_delta = -60

        payment_float = PaymentFloatImpact(
            clause_id=clause_id,
            baseline_terms=baseline,
            proposed_terms=proposed,
            float_delta_days=float_delta,
            cash_flow_narrative=(
                f"Party B's payment terms shift float by {float_delta} days "
                f"relative to baseline.  Negative values indicate accelerated "
                f"payment obligation for Party A."
            ) if float_delta != 0 else "No material float impact detected.",
            referenced_clauses=evidence_refs,
        )

    # ── Relationship Impact ──────────────────────────────────────────
    rel_risk = "neutral"
    rel_narrative = f"Clause {clause_id} changes are within normal negotiation range."
    is_aggressive = risk_profile.is_aggressive_deviation if risk_profile else False

    if is_aggressive:
        rel_risk = "adversarial"
        rel_narrative = (
            f"Aggressive deviation in {clause_id} may signal adversarial posture.  "
            f"Consider whether relationship preservation warrants concession."
        )
    elif risk_score >= 6.0:
        rel_risk = "negative"
        rel_narrative = (
            f"High-risk modifications in {clause_id} (score {risk_score:.1f}/10) "
            f"could strain the commercial relationship if not addressed collaboratively."
        )
    elif risk_score >= 3.0:
        rel_risk = "neutral"
        rel_narrative = (
            f"Moderate changes in {clause_id} — typical of active negotiation."
        )
    else:
        rel_risk = "positive"
        rel_narrative = (
            f"Minimal changes in {clause_id} — alignment is strong."
        )

    relationship = RelationshipImpact(
        clause_id=clause_id,
        relationship_risk=rel_risk,
        narrative=rel_narrative,
        referenced_clauses=evidence_refs,
    )

    # ── Commercial risk score ────────────────────────────────────────
    # Weight: ARR exposure most, payment next, relationship least
    commercial_risk = round(min(
        arr_exposure_pct * 0.08  # Normalise 0–80 → 0–6.4
        + (abs(payment_float.float_delta_days) * 0.03 if payment_float else 0.0)
        + {"positive": 0, "neutral": 1, "negative": 3, "adversarial": 5}.get(rel_risk, 1),
        10.0,
    ), 2)

    return CommercialLens(
        clause_id=clause_id,
        arr_impact=arr_impact,
        payment_float=payment_float,
        relationship=relationship,
        commercial_risk_score=commercial_risk,
        commercial_summary=(
            f"ARR exposure: {arr_exposure_pct:.0f}%.  "
            f"Relationship: {rel_risk}.  "
            f"Commercial risk: {commercial_risk}/10."
        ),
    )


def _build_candidate_comparison(
    neg_result: ClauseNegotiationResult,
    recommended_strategy: str,
) -> List[CandidateComparison]:
    """Build the comparison matrix from negotiation engine candidates."""
    comparisons: List[CandidateComparison] = []
    for c in neg_result.candidates:
        comparisons.append(CandidateComparison(
            strategy=c.strategy.value,
            label=c.label,
            party_a_utility=c.party_a_utility.weighted_total,
            party_b_utility=c.party_b_utility.weighted_total,
            compromise_score=c.compromise_score,
            is_recommended=(c.strategy.value == recommended_strategy),
            is_pareto_efficient=c.is_pareto_efficient,
            disqualification_reason=(
                "Exceeds variance ceiling" if c.exceeds_variance_ceiling else ""
            ),
        ))
    return comparisons


def _select_recommendation(
    neg_result: ClauseNegotiationResult,
    legal_risk: float,
    commercial_risk: float,
) -> Optional[CompromiseCandidate]:
    """
    Select the best candidate, preferring Pareto-efficient ones.

    Tie-breaking: if legal risk is high (≥7), prefer strategies that limit
    Party A exposure.  If commercial risk is high (≥7), prefer strategies
    that preserve the deal.
    """
    candidates = list(neg_result.pareto_frontier) if neg_result.pareto_frontier else list(neg_result.candidates)
    if not candidates:
        return neg_result.recommended

    # Filter out variance-ceiling violations unless everything violates
    within_ceiling = [c for c in candidates if not c.exceeds_variance_ceiling]
    pool = within_ceiling if within_ceiling else candidates

    # Sort by compromise_score, break ties by strategy preference
    strategy_order = {
        CompromiseStrategy.CONCEDE_WITH_GUARD: 0,
        CompromiseStrategy.SPLIT_MIDPOINT: 1,
        CompromiseStrategy.NARROW_SCOPE: 2,
        CompromiseStrategy.TRADE_OFF: 3,
        CompromiseStrategy.ACCEPT_PARTY_A: 4,
        CompromiseStrategy.ACCEPT_PARTY_B: 5,
        CompromiseStrategy.ESCALATE: 6,
    }

    # If legal risk is very high, penalise accept_party_b
    if legal_risk >= 7.0:
        strategy_order[CompromiseStrategy.ACCEPT_PARTY_B] = 10
        strategy_order[CompromiseStrategy.ACCEPT_PARTY_A] = 1

    # If commercial/relationship risk is high, penalise accept_party_a
    if commercial_risk >= 7.0:
        strategy_order[CompromiseStrategy.ACCEPT_PARTY_A] = 10
        strategy_order[CompromiseStrategy.CONCEDE_WITH_GUARD] = 0

    pool.sort(
        key=lambda c: (-c.compromise_score, strategy_order.get(c.strategy, 5)),
    )

    return pool[0]


def _compute_confidence(
    legal_risk: float,
    commercial_risk: float,
    candidate: Optional[CompromiseCandidate],
    is_non_negotiable: bool,
    has_aggressive_deviation: bool,
) -> float:
    """
    Arbiter confidence in the recommendation (0–100%).

    Formula:
        base = candidate.compromise_score (0–100)
        penalties:
            −15 if aggressive deviation
            −10 if combined risk ≥ 7
            −5  if combined risk ≥ 4
        bonuses:
            +10 if non-negotiable (clear path)
            +5  if Pareto-efficient

    Clamped to [10, 95] — never 0% (always some basis) and never 100%
    (human review always required).
    """
    if candidate is None:
        return 10.0

    base = candidate.compromise_score
    combined = legal_risk * 0.55 + commercial_risk * 0.45

    penalty = 0.0
    if has_aggressive_deviation:
        penalty += 15.0
    if combined >= 7.0:
        penalty += 10.0
    elif combined >= 4.0:
        penalty += 5.0

    bonus = 0.0
    if is_non_negotiable:
        bonus += 10.0
    if candidate.is_pareto_efficient:
        bonus += 5.0

    return round(max(10.0, min(95.0, base - penalty + bonus)), 1)


def _risk_label(score: float) -> str:
    if score >= 8.0:
        return "critical"
    elif score >= 6.0:
        return "high"
    elif score >= 3.5:
        return "moderate"
    return "low"


# ═════════════════════════════════════════════════════════════════════════════
# Agent Implementation
# ═════════════════════════════════════════════════════════════════════════════

class Agent3Arbiter(BaseAgent):
    """
    Agent 3: Arbiter-3 — AI Judge & Deal Mediator.

    Produces dual-lens verdicts (legal + commercial) for every contested
    clause, selects a recommended compromise from scored candidates, and
    generates proposed clause language.

    Inputs:
        • agent1_output  — LexIngestorAOutput (Party A baseline analysis)
        • agent2_output  — LexIngestorBOutput (Party B risk analysis)
        • negotiation_output — NegotiationEngineOutput (scored candidates)
        • financial_context — dict with arr_value, variance_ceiling, etc.
        • external_evidence — optional list of evidence dicts

    Guarantees:
        • Every claim references clause_id or evidence source
        • No invented laws or precedents presented as facts
        • Human review flagged as mandatory on every verdict
        • Deterministic fallback when no LLM key is available
    """

    def __init__(self, event_callback: Optional[EventCallback] = None):
        super().__init__(
            agent_id="a3",
            name="AI Judge & Deal Mediator",
            technical_name="Arbiter-3",
            event_callback=event_callback,
        )

    def _execute(
        self,
        agent1_output: Optional[LexIngestorAOutput] = None,
        agent2_output: Optional[LexIngestorBOutput] = None,
        negotiation_output: Optional[NegotiationEngineOutput] = None,
        financial_context: Optional[Dict[str, Any]] = None,
        external_evidence: Optional[List[Dict[str, Any]]] = None,
        matter_id: Optional[str] = None,
        **kwargs: Any,
    ) -> ArbiterOutput:
        self.emit_event(
            thought="Arbiter-3 commencing dual-lens deliberation on contested clauses...",
            matter_id=matter_id,
        )

        if not negotiation_output:
            raise ValueError(
                "Agent 3 requires negotiation_output (scored candidates from the negotiation engine)."
            )

        # Defaults
        if agent1_output is None:
            agent1_output = LexIngestorAOutput()
        if agent2_output is None:
            agent2_output = LexIngestorBOutput()
        if financial_context is None:
            financial_context = {}
        if external_evidence is None:
            external_evidence = []

        # Build lookup maps
        a1_map: Dict[str, ClassifiedClause] = {
            c.clause_id: c for c in agent1_output.classified_clauses
        }
        a2_map: Dict[str, ClauseRiskProfile] = {
            p.clause_id: p for p in agent2_output.clause_risk_profiles
        }
        a2_findings_map: Dict[str, List[RiskFinding]] = {}
        for profile in agent2_output.clause_risk_profiles:
            a2_findings_map[profile.clause_id] = profile.findings

        neg_map: Dict[str, ClauseNegotiationResult] = {
            r.clause_id: r for r in negotiation_output.clause_results
        }

        self.emit_event(
            thought=(
                f"Loaded context: {len(a1_map)} Party A clauses, "
                f"{len(a2_map)} risk profiles, "
                f"{len(neg_map)} negotiation results, "
                f"{len(external_evidence)} external evidence items."
            ),
            matter_id=matter_id,
        )

        # ── Route: LLM-enhanced or deterministic ────────────────────
        if settings.QWEN_API_KEY:
            try:
                self.emit_event(
                    thought=f"[Mode: LLM] Invoking Qwen LLM ({settings.QWEN_MODEL}) for semantic verdict enrichment...",
                    matter_id=matter_id,
                )
                logger.info(f"[AGENT 3] Mode: LLM | Attempting semantic verdict enrichment via Qwen ({settings.QWEN_MODEL}).")
                result = self._analyze_with_qwen(
                    agent1_output, agent2_output, negotiation_output,
                    financial_context, external_evidence,
                    a1_map, a2_map, a2_findings_map, neg_map,
                    matter_id,
                )
                logger.info("[AGENT 3] Mode: LLM | Successfully enriched verdicts via Qwen with deterministic validation.")
                return result
            except Exception as err:
                logger.warning(f"[AGENT 3] Qwen failed: {err}. Falling back to secondary provider or deterministic compromise scoring.")
        elif settings.GEMINI_API_KEY:
            try:
                self.emit_event(
                    thought="[Mode: LLM] Invoking Gemini for semantic verdict enrichment...",
                    matter_id=matter_id,
                )
                logger.info("[AGENT 3] Mode: LLM | Attempting semantic verdict enrichment via Gemini.")
                result = self._analyze_with_gemini(
                    agent1_output, agent2_output, negotiation_output,
                    financial_context, external_evidence,
                    a1_map, a2_map, a2_findings_map, neg_map,
                    matter_id,
                )
                logger.info("[AGENT 3] Mode: LLM | Successfully enriched verdicts via Gemini with deterministic validation.")
                return result
            except Exception as err:
                logger.warning(f"[AGENT 3] Gemini failed: {err}. Falling back to deterministic compromise scoring.")
        elif settings.OPENAI_API_KEY:
            try:
                self.emit_event(
                    thought="[Mode: LLM] Invoking OpenAI for semantic verdict enrichment...",
                    matter_id=matter_id,
                )
                logger.info("[AGENT 3] Mode: LLM | Attempting semantic verdict enrichment via OpenAI.")
                result = self._analyze_with_openai(
                    agent1_output, agent2_output, negotiation_output,
                    financial_context, external_evidence,
                    a1_map, a2_map, a2_findings_map, neg_map,
                    matter_id,
                )
                logger.info("[AGENT 3] Mode: LLM | Successfully enriched verdicts via OpenAI with deterministic validation.")
                return result
            except Exception as err:
                logger.warning(f"[AGENT 3] OpenAI failed: {err}. Falling back to deterministic compromise scoring.")

        # ── Deterministic fallback ──────────────────────────────────
        logger.info("[AGENT 3] Mode: FALLBACK | Using deterministic compromise scoring & Pareto arbitration.")
        self.emit_event(
            thought="[Mode: FALLBACK] Producing deterministic dual-lens verdicts & Nash equilibrium candidates...",
            matter_id=matter_id,
        )
        return self._deterministic_verdicts(
            negotiation_output, a1_map, a2_map, a2_findings_map, neg_map,
            financial_context, external_evidence, matter_id,
        )

    # ═════════════════════════════════════════════════════════════════════════
    # Deterministic Verdict Pipeline
    # ═════════════════════════════════════════════════════════════════════════

    def _deterministic_verdicts(
        self,
        negotiation_output: NegotiationEngineOutput,
        a1_map: Dict[str, ClassifiedClause],
        a2_map: Dict[str, ClauseRiskProfile],
        a2_findings_map: Dict[str, List[RiskFinding]],
        neg_map: Dict[str, ClauseNegotiationResult],
        financial_context: Dict[str, Any],
        external_evidence: List[Dict[str, Any]],
        matter_id: Optional[str],
    ) -> ArbiterOutput:
        verdicts: List[ClauseVerdict] = []
        escalated: List[str] = []
        legal_risks: List[float] = []
        commercial_risks: List[float] = []
        confidences: List[float] = []

        for neg_result in negotiation_output.clause_results:
            c_id = neg_result.clause_id
            category = neg_result.category
            title = neg_result.title
            section = neg_result.section_number

            a1_clause = a1_map.get(c_id)
            risk_profile = a2_map.get(c_id)
            findings = a2_findings_map.get(c_id, [])
            is_aggressive = risk_profile.is_aggressive_deviation if risk_profile else False

            # ── Build legal lens ─────────────────────────────────────
            legal_lens = _build_legal_lens(
                c_id, category, a1_clause, risk_profile, findings, external_evidence,
            )

            # ── Build commercial lens ────────────────────────────────
            commercial_lens = _build_commercial_lens(
                c_id, category, risk_profile, findings, financial_context,
            )

            # ── Select recommendation ────────────────────────────────
            recommended = _select_recommendation(
                neg_result,
                legal_lens.legal_risk_score,
                commercial_lens.commercial_risk_score,
            )

            # ── Build candidate comparison ───────────────────────────
            rec_strategy = recommended.strategy.value if recommended else ""
            comparison = _build_candidate_comparison(neg_result, rec_strategy)

            # ── Proposed clause text ─────────────────────────────────
            proposed_text = recommended.proposed_text if recommended else ""

            # ── Rationale (deterministic) ────────────────────────────
            rationale = self._build_deterministic_rationale(
                c_id, title, category, legal_lens, commercial_lens,
                recommended, neg_result.is_non_negotiable, is_aggressive,
            )

            # ── Confidence ───────────────────────────────────────────
            confidence = _compute_confidence(
                legal_lens.legal_risk_score,
                commercial_lens.commercial_risk_score,
                recommended,
                neg_result.is_non_negotiable,
                is_aggressive,
            )

            # ── Combined risk ────────────────────────────────────────
            combined_risk = round(
                legal_lens.legal_risk_score * 0.55
                + commercial_lens.commercial_risk_score * 0.45,
                2,
            )

            # ── Evidence trail ───────────────────────────────────────
            evidence_cited = list(legal_lens.evidence_references)
            for f in findings:
                evidence_cited.extend(f.deterministic_flags[:3])
            evidence_cited = list(dict.fromkeys(evidence_cited))

            # ── Escalation check ─────────────────────────────────────
            if recommended and recommended.strategy == CompromiseStrategy.ESCALATE:
                escalated.append(c_id)

            verdict = ClauseVerdict(
                clause_id=c_id,
                section_number=section,
                title=title,
                category=category,
                legal_lens=legal_lens,
                commercial_lens=commercial_lens,
                recommended_strategy=rec_strategy,
                recommended_label=recommended.label if recommended else "",
                proposed_clause_text=proposed_text,
                rationale=rationale,
                confidence=confidence,
                requires_human_review=True,
                candidate_comparison=comparison,
                combined_risk_score=combined_risk,
                evidence_cited=evidence_cited,
            )
            verdicts.append(verdict)
            legal_risks.append(legal_lens.legal_risk_score)
            commercial_risks.append(commercial_lens.commercial_risk_score)
            confidences.append(confidence)

        # ── Aggregates ───────────────────────────────────────────────
        n = len(verdicts) or 1
        agg_legal = round(sum(legal_risks) / n, 2)
        agg_commercial = round(sum(commercial_risks) / n, 2)
        agg_combined = round(agg_legal * 0.55 + agg_commercial * 0.45, 2)
        agg_confidence = round(sum(confidences) / n, 1)

        exec_summary = (
            f"Arbiter-3 reviewed {len(verdicts)} clause(s).  "
            f"Aggregate legal risk: {agg_legal}/10.  "
            f"Aggregate commercial risk: {agg_commercial}/10.  "
            f"Combined risk: {agg_combined}/10.  "
            f"Mean confidence: {agg_confidence}%.  "
            f"{len(escalated)} clause(s) escalated to human counsel.  "
            f"Human review is mandatory for all recommendations."
        )

        self.emit_event(thought=exec_summary, matter_id=matter_id)

        return ArbiterOutput(
            matter_id=matter_id,
            verdicts=verdicts,
            aggregate_legal_risk=agg_legal,
            aggregate_commercial_risk=agg_commercial,
            aggregate_combined_risk=agg_combined,
            aggregate_confidence=agg_confidence,
            escalated_clause_ids=escalated,
            executive_summary=exec_summary,
            human_review_required=True,
        )

    def _build_deterministic_rationale(
        self,
        clause_id: str,
        title: str,
        category: str,
        legal_lens: LegalLens,
        commercial_lens: CommercialLens,
        recommended: Optional[CompromiseCandidate],
        is_non_negotiable: bool,
        is_aggressive: bool,
    ) -> str:
        """Build an explainable rationale string referencing evidence."""
        if recommended is None:
            return f"No candidates available for {clause_id}.  Manual drafting required."

        parts: List[str] = []

        # Opening
        strategy_label = recommended.strategy.value.replace("_", " ").title()
        parts.append(
            f"For clause {clause_id} ({title}), the Arbiter recommends "
            f"'{strategy_label}' (compromise score: {recommended.compromise_score}/100)."
        )

        # Non-negotiable override
        if is_non_negotiable:
            parts.append(
                f"This clause is flagged as non-negotiable by Party A — "
                f"the baseline position is enforced (ref: {clause_id})."
            )
            return "  ".join(parts)

        # Legal basis
        parts.append(
            f"Legal risk: {legal_lens.legal_risk_score}/10.  "
            f"{legal_lens.legal_summary}"
        )

        # Commercial basis
        parts.append(
            f"Commercial risk: {commercial_lens.commercial_risk_score}/10.  "
            f"{commercial_lens.commercial_summary}"
        )

        # Aggressive deviation warning
        if is_aggressive:
            parts.append(
                f"⚠ Aggressive deviation detected in {clause_id}.  "
                f"Party B's markup represents a material departure from baseline."
            )

        # Utility comparison
        parts.append(
            f"Party A utility: {recommended.party_a_utility.weighted_total}, "
            f"Party B utility: {recommended.party_b_utility.weighted_total}, "
            f"joint surplus: {recommended.joint_surplus}, "
            f"balance: {recommended.balance}."
        )

        # Evidence trail
        refs = legal_lens.evidence_references[:5]
        if refs:
            parts.append(f"Evidence cited: {', '.join(refs)}.")

        # Human review reminder
        parts.append(
            "This recommendation requires mandatory human counsel review "
            "before adoption."
        )

        return "  ".join(parts)

    # ═════════════════════════════════════════════════════════════════════════
    # LLM-Enhanced: Qwen
    # ═════════════════════════════════════════════════════════════════════════

    def _analyze_with_qwen(
        self,
        agent1_output: LexIngestorAOutput,
        agent2_output: LexIngestorBOutput,
        negotiation_output: NegotiationEngineOutput,
        financial_context: Dict[str, Any],
        external_evidence: List[Dict[str, Any]],
        a1_map: Dict[str, ClassifiedClause],
        a2_map: Dict[str, ClauseRiskProfile],
        a2_findings_map: Dict[str, List[RiskFinding]],
        neg_map: Dict[str, ClauseNegotiationResult],
        matter_id: Optional[str],
    ) -> ArbiterOutput:
        from app.services.llm_client import call_qwen_chat

        det_result = self._deterministic_verdicts(
            negotiation_output, a1_map, a2_map, a2_findings_map, neg_map,
            financial_context, external_evidence, matter_id,
        )

        prompt = self._build_llm_prompt(det_result, financial_context, external_evidence)
        raw_text = call_qwen_chat(prompt, json_mode=True)

        return self._merge_llm_enrichment(raw_text, det_result, matter_id)

    # ═════════════════════════════════════════════════════════════════════════
    # LLM-Enhanced: Gemini
    # ═════════════════════════════════════════════════════════════════════════

    def _analyze_with_gemini(
        self,
        agent1_output: LexIngestorAOutput,
        agent2_output: LexIngestorBOutput,
        negotiation_output: NegotiationEngineOutput,
        financial_context: Dict[str, Any],
        external_evidence: List[Dict[str, Any]],
        a1_map: Dict[str, ClassifiedClause],
        a2_map: Dict[str, ClauseRiskProfile],
        a2_findings_map: Dict[str, List[RiskFinding]],
        neg_map: Dict[str, ClauseNegotiationResult],
        matter_id: Optional[str],
    ) -> ArbiterOutput:
        import google.generativeai as genai

        genai.configure(api_key=settings.GEMINI_API_KEY)
        model = genai.GenerativeModel("gemini-1.5-flash")

        # Get deterministic baseline
        det_result = self._deterministic_verdicts(
            negotiation_output, a1_map, a2_map, a2_findings_map, neg_map,
            financial_context, external_evidence, matter_id,
        )

        # Enrich each verdict with LLM semantic analysis
        prompt = self._build_llm_prompt(det_result, financial_context, external_evidence)
        response = model.generate_content(prompt)
        raw_text = response.text

        return self._merge_llm_enrichment(raw_text, det_result, matter_id)

    # ═════════════════════════════════════════════════════════════════════════
    # LLM-Enhanced: OpenAI
    # ═════════════════════════════════════════════════════════════════════════

    def _analyze_with_openai(
        self,
        agent1_output: LexIngestorAOutput,
        agent2_output: LexIngestorBOutput,
        negotiation_output: NegotiationEngineOutput,
        financial_context: Dict[str, Any],
        external_evidence: List[Dict[str, Any]],
        a1_map: Dict[str, ClassifiedClause],
        a2_map: Dict[str, ClauseRiskProfile],
        a2_findings_map: Dict[str, List[RiskFinding]],
        neg_map: Dict[str, ClauseNegotiationResult],
        matter_id: Optional[str],
    ) -> ArbiterOutput:
        from openai import OpenAI

        client = OpenAI(api_key=settings.OPENAI_API_KEY)

        # Get deterministic baseline
        det_result = self._deterministic_verdicts(
            negotiation_output, a1_map, a2_map, a2_findings_map, neg_map,
            financial_context, external_evidence, matter_id,
        )

        # Enrich each verdict with LLM semantic analysis
        prompt = self._build_llm_prompt(det_result, financial_context, external_evidence)
        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[{"role": "user", "content": prompt}],
            response_format={"type": "json_object"},
        )
        raw_text = response.choices[0].message.content or "{}"

        return self._merge_llm_enrichment(raw_text, det_result, matter_id)

    # ═════════════════════════════════════════════════════════════════════════
    # LLM Prompt & Merge
    # ═════════════════════════════════════════════════════════════════════════

    def _build_llm_prompt(
        self,
        det_result: ArbiterOutput,
        financial_context: Dict[str, Any],
        external_evidence: List[Dict[str, Any]],
    ) -> str:
        """Short, structured prompt for LLM enrichment."""
        # Compact verdict summaries for the prompt
        clause_summaries = []
        for v in det_result.verdicts[:20]:
            clause_summaries.append({
                "clause_id": v.clause_id,
                "title": v.title,
                "category": v.category,
                "legal_risk": v.legal_lens.legal_risk_score,
                "commercial_risk": v.commercial_lens.commercial_risk_score,
                "legal_summary": v.legal_lens.legal_summary[:150],
                "commercial_summary": v.commercial_lens.commercial_summary[:150],
                "recommended_strategy": v.recommended_strategy,
                "proposed_text": v.proposed_clause_text[:200],
            })

        return f"""You are Arbiter-3, an AI mediator producing dual-lens verdicts.

For each clause below, provide semantic enrichment.  Output ONLY valid JSON:
{{
  "enrichments": [
    {{
      "clause_id": "string (MUST match input)",
      "legal_rationale": "string (1-2 sentences, legal perspective)",
      "commercial_rationale": "string (1-2 sentences, commercial perspective)",
      "improved_proposed_text": "string (refined clause language, or empty to keep current)",
      "confidence_adjustment": float (-10 to +10, adjustment to deterministic confidence),
      "additional_evidence_notes": "string (any relevant context, NO invented citations)"
    }}
  ],
  "executive_summary": "string (2-3 sentence overall assessment)"
}}

Rules:
- Reference ONLY clause_ids provided below.
- Do NOT invent laws, case names, or regulatory citations.
- Do NOT present AI analysis as legal advice.
- Keep responses concise.

CLAUSES:
{json.dumps(clause_summaries, indent=2)}

FINANCIAL CONTEXT:
{json.dumps(financial_context, indent=2)}

EXTERNAL EVIDENCE:
{json.dumps(external_evidence[:10], indent=2)}"""

    def _merge_llm_enrichment(
        self,
        raw_text: str,
        det_result: ArbiterOutput,
        matter_id: Optional[str],
    ) -> ArbiterOutput:
        """Merge LLM enrichments into deterministic verdicts."""
        llm_data = self.parse_structured_output(raw_text)
        enrichments: Dict[str, Dict[str, Any]] = {}

        if isinstance(llm_data, dict):
            for e in llm_data.get("enrichments", []):
                cid = e.get("clause_id", "")
                if cid:
                    enrichments[cid] = e

        for verdict in det_result.verdicts:
            enrichment = enrichments.get(verdict.clause_id)
            if not enrichment:
                continue

            # Enrich rationale
            legal_rat = enrichment.get("legal_rationale", "")
            commercial_rat = enrichment.get("commercial_rationale", "")
            if legal_rat:
                verdict.rationale = (
                    f"{verdict.rationale}  "
                    f"[LLM Legal Insight] {legal_rat}"
                )
            if commercial_rat:
                verdict.rationale = (
                    f"{verdict.rationale}  "
                    f"[LLM Commercial Insight] {commercial_rat}"
                )

            # Improved proposed text
            improved = enrichment.get("improved_proposed_text", "")
            if improved and improved.strip():
                verdict.proposed_clause_text = improved

            # Confidence adjustment
            adj = float(enrichment.get("confidence_adjustment", 0.0))
            verdict.confidence = round(
                max(10.0, min(95.0, verdict.confidence + adj)), 1,
            )

            # Additional evidence notes
            notes = enrichment.get("additional_evidence_notes", "")
            if notes:
                verdict.evidence_cited.append(f"[LLM] {notes[:100]}")

        # Update executive summary with LLM enrichment
        llm_summary = ""
        if isinstance(llm_data, dict):
            llm_summary = llm_data.get("executive_summary", "")

        if llm_summary:
            det_result.executive_summary = (
                f"{llm_summary}  "
                f"[Deterministic basis] {det_result.executive_summary}"
            )

        # Recalculate aggregate confidence
        if det_result.verdicts:
            det_result.aggregate_confidence = round(
                sum(v.confidence for v in det_result.verdicts) / len(det_result.verdicts),
                1,
            )

        det_result.matter_id = matter_id

        self.emit_event(
            thought=f"LLM enrichment merged.  {det_result.executive_summary}",
            matter_id=matter_id,
        )

        return det_result
